# Generated by Django 4.2.1 on 2023-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='test team', max_length=200),
            preserve_default=False,
        ),
    ]
