# Generated by Django 4.2.1 on 2023-05-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
